"""add query_profiles, model_registry, experiment tracking tables

Revision ID: 601a04e04640
Revises: e0623d15ed90
Create Date: 2026-08-28 00:27:23.540545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '601a04e04640'
down_revision: Union[str, Sequence[str], None] = 'e0623d15ed90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('experiment_name', sa.Text(), nullable=False),
    sa.Column('component', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.Text(), nullable=False),
    sa.Column('algorithm_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_benchmarks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('model_key', sa.Text(), nullable=False),
    sa.Column('benchmark_name', sa.Text(), nullable=False),
    sa.Column('latency_ms_p50', sa.Numeric(), nullable=True),
    sa.Column('latency_ms_p95', sa.Numeric(), nullable=True),
    sa.Column('latency_ms_p99', sa.Numeric(), nullable=True),
    sa.Column('cold_start_ms', sa.Numeric(), nullable=True),
    sa.Column('warm_latency_ms', sa.Numeric(), nullable=True),
    sa.Column('throughput_qps', sa.Numeric(), nullable=True),
    sa.Column('device', sa.Text(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('model_key', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('model_family', sa.Text(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameter_count', sa.BigInteger(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('latency_class', sa.Text(), nullable=True),
    sa.Column('cost_class', sa.Text(), nullable=True),
    sa.Column('local_or_remote', sa.Text(), nullable=False),
    sa.Column('hardware_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('revision', sa.Text(), nullable=True),
    sa.Column('availability_status', sa.Text(), nullable=False),
    sa.Column('known_strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('known_weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_key')
    )
    op.create_table('experiment_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('experiment_id', sa.Text(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hardware', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('code_commit', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_profiles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('data_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('complexity', sa.Text(), nullable=False),
    sa.Column('sensitivity', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('actionability', sa.Text(), nullable=False),
    sa.Column('risk_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capability_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_results',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('experiment_run_id', sa.Text(), nullable=False),
    sa.Column('split', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_run_id'], ['experiment_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_results')
    op.drop_table('query_profiles')
    op.drop_table('experiment_runs')
    op.drop_table('model_registry')
    op.drop_table('model_benchmarks')
    op.drop_table('experiments')
    # ### end Alembic commands ###
