"""add response_evaluations table

Revision ID: 6a6db1b4feff
Revises: 8038ec63a9b9
Create Date: 2026-08-28 03:58:55.204239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a6db1b4feff'
down_revision: Union[str, Sequence[str], None] = '8038ec63a9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_evaluations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('trajectory_id', sa.Text(), nullable=False),
    sa.Column('evaluator', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_evaluations')
    # ### end Alembic commands ###
