"""add route_decisions table

Revision ID: 8038ec63a9b9
Revises: 601a04e04640
Create Date: 2026-08-28 02:23:09.784321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8038ec63a9b9'
down_revision: Union[str, Sequence[str], None] = '601a04e04640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_decisions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('trajectory_id', sa.Text(), nullable=False),
    sa.Column('query_profile_id', sa.Text(), nullable=True),
    sa.Column('capability_router_version', sa.Text(), nullable=False),
    sa.Column('selected_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('restricted_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capability_reason', sa.Text(), nullable=False),
    sa.Column('execution_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_router_version', sa.Text(), nullable=False),
    sa.Column('model_action', sa.Text(), nullable=False),
    sa.Column('model_role', sa.Text(), nullable=True),
    sa.Column('require_verification', sa.Boolean(), nullable=False),
    sa.Column('human_approval_required', sa.Boolean(), nullable=False),
    sa.Column('model_reason', sa.Text(), nullable=False),
    sa.Column('expected_cost_class', sa.Text(), nullable=True),
    sa.Column('expected_latency_class', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_decisions')
    # ### end Alembic commands ###
