"""add decision, intervention, replan, verification tables

Revision ID: d758162727ad
Revises: 6a6db1b4feff
Create Date: 2026-08-28 10:27:14.643966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd758162727ad'
down_revision: Union[str, Sequence[str], None] = '6a6db1b4feff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('trajectory_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('triggering_evaluator', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('can_retry', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replans',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('trajectory_id', sa.Text(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('from_plan_version', sa.Integer(), nullable=False),
    sa.Column('to_plan_version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifications',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('trajectory_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('checked_evaluators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('trajectory_id', sa.Text(), nullable=False),
    sa.Column('decision_id', sa.Text(), nullable=False),
    sa.Column('intervention_type', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_effect', sa.Text(), nullable=False),
    sa.Column('actual_effect', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('route_decisions', sa.Column('plan_version', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('route_decisions', 'plan_version', server_default=None)
    # ### end Alembic commands ###
    # (server_default backfills existing rows to plan_version=1, matching
    # the ORM model's Python-side default; then dropped so it doesn't
    # silently mask a future ORM bug that forgets to set it.)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_decisions', 'plan_version')
    op.drop_table('interventions')
    op.drop_table('verifications')
    op.drop_table('replans')
    op.drop_table('decisions')
    # ### end Alembic commands ###
