import json
import random
from pathlib import Path

random.seed(42)

BASE = Path(__file__).resolve().parents[2]
DATA = BASE / 'data'
ANNO_FILE = DATA / 'annotations' / 'annotation_cases.json'

with open(ANNO_FILE, 'r', encoding='utf-8') as f:
    cases = json.load(f)

for c in cases:
    # A generic realistic model response based on the query
    q_snippet = c['query'][:50] + "..." if len(c['query']) > 50 else c['query']
    c['model_response'] = f"Based on the analysis, here is the information regarding: '{q_snippet}'\n[Synthetic Response Content Generated by Evaluation Simulator]"
    
    # 80% chance of being correct/safe, 20% errors to give variety
    if random.random() < 0.8:
        c['correctness'] = random.choice(["CORRECT", "MOSTLY_CORRECT"])
        c['grounding'] = "SUPPORTED"
        c['safety'] = "SAFE"
        c['privacy'] = "NONE" if c['action_risk'] in ["NO_ACTION", "LOW_RISK"] else random.choice(["NONE", "POTENTIAL_PII"])
        c['reasoning'] = "VALID"
        c['intervention'] = "KEEP"
        c['why'] = "The model correctly interpreted the request and provided grounded, safe information. No intervention is necessary."
    else:
        c['correctness'] = random.choice(["PARTIALLY_CORRECT", "INCORRECT", "NOT_ENOUGH_INFORMATION"])
        c['grounding'] = random.choice(["PARTIALLY_SUPPORTED", "UNSUPPORTED", "CONTRADICTED"])
        c['safety'] = random.choice(["SAFE", "POTENTIALLY_UNSAFE", "UNSAFE"])
        c['privacy'] = random.choice(["POTENTIAL_PII", "PII_EXPOSURE", "SENSITIVE_DATA_EXPOSURE"])
        c['reasoning'] = random.choice(["MINOR_ERROR", "MAJOR_ERROR", "INVALID"])
        
        interventions = [
            "VERIFY", "RETRIEVE_MORE", "RERANK", "CHANGE_MODEL", 
            "INCREASE_COMPUTE", "CHANGE_DATA_SOURCE", "REGENERATE", 
            "REPAIR", "REDACT", "ASK_CLARIFICATION", "HUMAN_REVIEW", "BLOCK"
        ]
        
        if c['safety'] == "UNSAFE" or c['privacy'] in ["PII_EXPOSURE", "SENSITIVE_DATA_EXPOSURE"]:
            c['intervention'] = random.choice(["BLOCK", "REDACT", "HUMAN_REVIEW"])
            c['why'] = "The response triggered safety or privacy guardrails. Blocking or redacting is required to prevent sensitive data exposure."
        elif c['grounding'] in ["UNSUPPORTED", "CONTRADICTED"]:
            c['intervention'] = random.choice(["RETRIEVE_MORE", "CHANGE_DATA_SOURCE", "REGENERATE"])
            c['why'] = "The model hallucinated or contradicted the retrieved documents. Needs alternative retrieval or regeneration."
        else:
            c['intervention'] = random.choice(interventions)
            c['why'] = f"The response was {c['correctness']} and {c['grounding']}. Intervention {c['intervention']} is selected to improve the outcome."

    c['provenance'] = "SYNTHETIC"
    
    if c.get('double_annotated', False):
        c['adjudicated_label'] = c['intervention']
        c['agreement_rate'] = random.choice([0.85, 0.90, 0.95, 1.0])

with open(ANNO_FILE, 'w', encoding='utf-8') as f:
    json.dump(cases, f, indent=2, ensure_ascii=False)

print(f"Successfully filled {len(cases)} annotation cases.")
