"""Cross-encoder reranker -- the real learned reranking stage that
Milestone 4/5 explicitly deferred (`docs/PROJECT_STATE/DECISIONS.md`:
"RAG 'reranking' is min-max score fusion (dense+lexical), not a
cross-encoder... considered and deferred given this milestone's already
large scope, not because it's expected to be worse").

Model: cross-encoder/ms-marco-MiniLM-L-6-v2, revision
c5ee24cb16019beea0893ab7796b1df96625c6b8 (pinned; verified via the live
Hugging Face API -- MS MARCO passage-ranking cross-encoder, ~23M
parameters, ~90MB, Apache-2.0). Already fully cached locally before this
milestone started (no download needed). CPU inference on this corpus's
scale (dozens of candidate chunks per query) is fast -- see
docs/EVALUATION/RAG_RESULTS.md for measured latency; this is a
NO-GPU-DEMONSTRATION-ENVIRONMENT component per the bootstrap's local
model latency policy, not a reason to avoid it.

Distinct from ``controlplane.rag.retrieval``'s dense+BM25 score fusion:
that stage generates and ranks *candidates* from the full corpus cheaply;
this stage re-scores a much smaller candidate set with a model trained
specifically for query/passage relevance (real cross-attention between
query and passage, not two independently-encoded vectors compared by
cosine similarity or an unweighted lexical/dense blend).

Offline-first (bootstrap's "do not silently download during a request"
principle, already applied to ``local_hf_provider.py``): ``local_files_only=True``.
"""

from __future__ import annotations

import math
import time
from dataclasses import replace
from functools import lru_cache
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from controlplane.rag.retrieval import RetrievedChunk

MODEL_REPO = "cross-encoder/ms-marco-MiniLM-L-6-v2"
MODEL_REVISION = "c5ee24cb16019beea0893ab7796b1df96625c6b8"


class RerankerError(Exception):
    pass


def _sigmoid(x: float) -> float:
    return 1.0 / (1.0 + math.exp(-x))


class CrossEncoderReranker:
    name = "cross_encoder_ms_marco_minilm_l6_v2"

    def __init__(self) -> None:
        try:
            from sentence_transformers import CrossEncoder
        except ImportError as exc:
            raise RerankerError(
                "sentence-transformers is not installed; run pip install -e \".[dev]\""
            ) from exc

        try:
            self._model = CrossEncoder(MODEL_REPO, revision=MODEL_REVISION, local_files_only=True)
        except Exception as exc:
            raise RerankerError(
                f"local model {MODEL_REPO}@{MODEL_REVISION} is not cached locally -- "
                "download it once via huggingface_hub.snapshot_download during setup, "
                "never during a request"
            ) from exc
        self.last_latency_ms: int | None = None

    def rerank(self, query: str, candidates: list["RetrievedChunk"], top_k: int | None = None) -> list["RetrievedChunk"]:
        """Re-scores ``candidates`` (already-generated by dense+BM25
        fusion) with the cross-encoder and returns them re-sorted by
        ``cross_encoder_score`` descending, truncated to ``top_k``.
        Preserves ``dense_score``/``lexical_score``/``fused_score`` on
        each item so callers/experiments can compare all signals."""
        if not candidates:
            return []
        pairs = [(query, c.chunk.text) for c in candidates]
        start = time.monotonic()
        raw_scores = self._model.predict(pairs)
        self.last_latency_ms = int((time.monotonic() - start) * 1000)

        rescored = [
            replace(c, cross_encoder_score=_sigmoid(float(s)))
            for c, s in zip(candidates, raw_scores)
        ]
        rescored.sort(key=lambda c: c.cross_encoder_score, reverse=True)
        return rescored[:top_k] if top_k is not None else rescored


@lru_cache(maxsize=1)
def get_reranker() -> CrossEncoderReranker:
    return CrossEncoderReranker()
